### ISSUE TITLE
请问一下大佬，fashion minist刷分题的submission.csv上传提交方式？

### ISSUE THREAD

**Issue by nickliqian** [monkeyDemon/Learn_Dive-into-DL-PyTorch#2]
submission.csv上传提交的方式和入口链接。

**Comment by monkeyDemon** [comment]
> submission.csv上传提交的方式和入口链接。

进入kesci网站并登录 www.kesci.com
依次点击 左侧导航栏模块应用->课程列表->动手学深度学习->课程作业 即可找到提交的入口

**Comment by nickliqian** [comment]
@monkeyDemon 找到嘞，谢谢大佬！
